apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: istio-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: istio-operator
      sourceRef:
        kind: GitRepository
        name: istio-repo
        namespace: istio-system
      interval: 1m
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: istio-repo
  namespace: istio-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/istio/istio.git
    ignore: |
    # exclude all
    !/manifests/charts/istio-operator
