apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-config-ingressgateways # REQUIRED
  namespace: istio-system
spec:
  profile: empty # REQUIRED
  components:
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway-a
  addonComponents:
    kiali:
      enabled: true
      namespace: monitoring
    tracing:
      enabled: true
      namespace: monitoring
 